name: Sync labels

on:
  push:
    branches: [main]
    paths:
      - labels.yml
  workflow_dispatch:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Yggdrasil-Labs/.github
          ref: main

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: labels.yml
          skip-delete: false  # 设置为 true 时不会删除仓库中已有的额外标签
