name: Sync labels (self)

on:
  push:
    branches: [main]
    paths:
      - labels.yml
  workflow_dispatch:

jobs:
  sync:
    uses: Yggdrasil-Labs/.github/.github/workflows/sync-labels.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
